# уровень логов - debug|info|warning|error, по умолчанию warning, необязательный параметр
logLevel: debug
# как будут выводиться логи, в консоль или файл
#logOutput: stdout | /path/to/file, по умолчанию stdout, необязательный параметр
# селектор dkim, по умолчанию mail, необязательный параметр
dkimSelector: trololo
# приватный ключ, публичный ключ должен быть прописан в DNS
privateKey: /path/to/private/key_rsa

# получатели писем
consumers:
  # серверы, с которых получаем письма
  - uri: amqp://guest:guest@127.0.0.1:5672/postmanq
    bindings:
      - # имя обменника
        exchange: postmanq
        # имя очереди
        queue: postmanq
        # direct|fanout|topic, по умолчанию fanout, необязательный параметр
        type: fanout
        # по умолчанию пустая строка, необязательный параметр
        # routing: outbox
        # количество обработчиков очереди, по умолчанию 1, необязательный параметр
        handlers: 20
      # - # если указано name, тогда обменник и очередь именуются одинаково
      #  name: second

# отправители писем
mailers:
  - # IP, с которого отправляем письма
    uri: 176.74.15.206:25
    # количество потоков, с которых отправляем письма
    handlers: 30

# лимиты
limits:
  # хост почтовика
  gmail.com:
    # период, за который учитываем количество отправленных писем, возможные значения - second|minute|hour|day
    type: day
    # максимальное количество писем, которое может быть отправлено за период
    value: 2000
  mail.ru:
    type: second
    value: 1
  yandex.ru:
    type: day
    value: 150