#logLevel: info # debug|info|warning|error, по умолчанию warning
logLevel: debug
#output: stdout | /path/to/file, по умолчанию stdout
consumers:
#  - uri: amqp://guest:guest@10.1.0.1:5672/postmanq
  - uri: amqp://guest:guest@127.0.0.1:5672/postmanq
#  - uri: amqp://guest:guest@127.0.0.1:5672/sale
    bindings:
      - # имя обменника
        exchange: postmanq
#        exchange: amqp.mailerq.message.exchange
        # имя очереди
        queue: postmanq
#        queue: amqp.mailerq.message.queue
        # direct|fanout|topic, по умолчанию fanout
        # type: direct
        # по умолчанию пустая строка
        # routing: outbox
        # количество обработчиков очереди, по умолчанию 1
        handlers: 20
#      - # если указано name, тогда обменник и очередь именуются одинаково
#        name: second
#  - uri: amqp://guest:guest@192.168.0.1:5672/path1
#    bindings:
#      - name: third
#      - exchange: fourth
#        queue: fourth

dkimSelector: mail
privateKey: /home/solomonov/postmanq/src/github.com/byorty/postmanq/postmanq_rsa
mailers:
#  - uri: smtp://username:password@host:25
#  - uri: mta://10.222.0.1:25
#  - uri: local://10.222.0.1:25
#  - uri: local://88.208.2.6:25
#    handlers: 10
#  - uri: smtp://smtp.gmail.com:587
#    username: asolomonoff@gmail.com
#    password: asolomonoff001
  - uri: mta://176.74.15.206:25
    handlers: 20
#    handlers: 10
