debug: true
#output: stdout | /path/to/file, по умолчанию stdout
consumers:
  - uri: amqp://guest:guest@10.1.0.1:5672/postmanq
    bindings:
      - # имя обменника
        exchange: postmanq
        # имя очереди
        queue: postmanq
        # direct|fanout|topic, по умолчанию direct
        type: direct
        # по умолчанию пустая строка
        routing: outbox
        # количество обработчиков очереди, по умолчанию 1
        handlers: 20
      - # если указано name, тогда обменник и очередь именуются одинаково
        name: second
#  - uri: amqp://guest:guest@192.168.0.1:5672/path1
#    bindings:
#      - name: third
#      - exchange: fourth
#        queue: fourth

mailers:
#  - uri: smtp://username:password@host:25
  - uri: smtp://username:password@10.222.0.1:25
