# получатели писем, обязательный параметр
consumers:

  # серверы, с которых получаем письма
  - uri: amqp://guest:guest@127.0.0.1:5672/postmanq

    assistants:

      # имя обменника
      - exchange: example

        # имя очереди
        queue: example

        # direct|fanout|topic, по умолчанию fanout, необязательный параметр
        type: fanout

        # по умолчанию пустая строка, необязательный параметр
        routing: example

        # количество обработчиков очереди, по умолчанию количество ядер процессора, необязательный параметр
        workers: 20

        dest:
          example1.com: postmanq1
          example2.com: postmanq2
          example3.com: postmanq3

    bindings:

      # имя обменника
      - exchange: postmanq

        # имя очереди
        queue: postmanq

        # direct|fanout|topic, по умолчанию fanout, необязательный параметр
        type: fanout

        # по умолчанию пустая строка, необязательный параметр
        # routing: outbox

        # количество обработчиков очереди, по умолчанию количество ядер процессора, необязательный параметр
        workers: 20

      # - если указано name, тогда обменник и очередь именуются одинаково
      #  name: second

# количество потоков для проверки лимитов, создания подключений, отправки писем, по умолчанию количество ядер процессора, необязательный параметр
workers: 20

# таймауты, необязательный параметр
timeouts:
  # насколько поток будет засыпать, пока не появится свободное соединение и т.д, необязательный параметр, по умолчанию секунда
  sleep: 1s

  # время ожидания отправки новых писем, по истечении времени соединение закрывается, необязательный параметр, по умолчанию 30 секунд
  waiting: 30s

  # время ожидания создания нового соединения с почтовым сервисом, необязательный параметр, по умолчанию 5 минут
  connection: 5m

  # время ожидания ответа команде HELLO, необязательный параметр, по умолчанию 5 минут
  hello: 5m

  # время ожидания ответа команде MAIL, необязательный параметр, по умолчанию 5 минут
  mail: 5m

  # время ожидания ответа команде RCPT, необязательный параметр, по умолчанию 5 минут
  rcpt: 5m

  # время ожидания ответа команде DATA, необязательный параметр, по умолчанию 10 минут
  data: 10m

# домены, с которых будут рассылаться письма, обязательный параметр
domains:

  # настройки для домена
  example.com:
    # уровень логов - debug|info|warning|error, по умолчанию warning, необязательный параметр
    logLevel: debug

    # как будут выводиться логи, в консоль или файл, stdout | /path/to/file, по умолчанию stdout, необязательный параметр
    logOutput: stdout

    # селектор dkim, по умолчанию mail, необязательный параметр
    dkimSelector: mail

    # приватный ключ, публичный ключ должен быть прописан в DNS
    privateKey: /path/to/private/key_rsa1

    # сертификат, используется для создания TLS соединений
    certificate: /path/to/cert1

    # ip, с которых будем рассылать письма
    ips: [1.1.1.1, 2.2.2.2, 3.3.3.3]

    # домены исключенные из рассылки, необязательный параметр
    exclude: [bad.address1.com, bad.address2.com]

    # лимиты, необязательный параметр
    limits:

      # хост почтового сервиса
      yandex.ru:

        # период, за который учитываем количество отправленных писем, возможные значения - second|minute|hour|day
        type: day

        # максимальное количество писем, которое может быть отправлено за период
        value: 150